package com.exmaple.MyFirstMVC2;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;

/*
 * This is your one, and still only, main.
 */
// This SpringBootApplication annotation, is autogenerated
// Configures your Spring App and enables Component Scanning
@SpringBootApplication
// The Component Scan will look through your application
// for all the "Spring Beans" (Annotated things)
// DO NOT FORGET THIS IN YOUR PROJECT, OR NOTIHNG WILL WORK!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// the base packages are the folders your spring beans (java code) are in
// give the exact name of your project packages ex: com.(WhateverYouNameIt)
@ComponentScan(basePackages = "com.exmaple")
public class MyFirstMvc2Application {
	public static void main(String[] args) {
		SpringApplication.run(MyFirstMvc2Application.class, args);
	}

}
